
	LIST    P=16F887

	#include <P16f887.INC>

    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF



	ORG 0X00
	GOTO INICIO

	ORG 0X05
    INICIO
	BANKSEL ANSELH
	CLRF    ANSELH
	CLRF    ANSEL
	BANKSEL TRISB
	MOVLW   B'11110000'
	MOVWF   TRISB
	CLRF    TRISC
	BANKSEL PORTC
	CLRF    PORTC

    MAIN
	CLRF    PORTB
	BTFSS   PORTB,RB4
	CALL    FILA1_C1
	BTFSS   PORTB,RB5
	CALL    FILA1_C2
	BTFSS	PORTB,RB6
	CALL	FILA1_C3
	BTFSS	PORTB,RB6
	CALL	FILA1_C4
	GOTO    MAIN

    FILA1_C1
	MOVLW   .14		;SOLO RB0 EN BAJO
	MOVWF   PORTB	;PORTB
	BTFSC   PORTB,RB4	;SI ESTA EN 0 -> DATO1 
	GOTO    FILA2_C1
	CALL    DATO1
	RETURN

    FILA2_C1
	MOVLW   .13
	MOVWF   PORTB
	BTFSC   PORTB,RB4
	GOTO    FILA3_C1
	CALL    DATO3
	RETURN
    FILA3_C1
	MOVLW   .11
	MOVWF   PORTB
	BTFSC   PORTB,RB4
	GOTO    FILA4_C1
	CALL    DATO5
	RETURN
    FILA4_C1
	MOVLW   .7
	MOVWF   PORTB
	BTFSC   PORTB,RB4
	GOTO    $+2
	CALL    DATO7
	RETURN
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;COLUMNA 2;;;;;;;;;;;;;;;;;;;;;;;;;;;;,

    FILA1_C2
	MOVLW   .14		;SOLO RB0 EN BAJO
	MOVWF   PORTB	;PORTB
	BTFSC   PORTB,RB5	;SI ESTA EN 0 -> DATO1 
	GOTO    FILA2_C2
	CALL    DATO2
	RETURN

    FILA2_C2
	MOVLW   .13
	MOVWF   PORTB
	BTFSC   PORTB,RB5
	GOTO    FILA3_C2
	CALL    DATO4
	RETURN
    FILA3_C2
	MOVLW   .11
	MOVWF   PORTB
	BTFSC   PORTB,RB5
	GOTO    FILA4_C2
	CALL    DATO6
	RETURN
    FILA4_C2
	MOVLW   .7
	MOVWF   PORTB
	BTFSC   PORTB,RB5
	GOTO    $+2
	CALL    DATO8
	RETURN
       ;;;;;;;;;;;;;;;;;;;;;;;;DATOS DE LA COLUMNA;;;;;;;;;;;;
    DATO1
	MOVLW   .
	MOVWF   PORTC
	RETURN
    DATO3
	MOVLW   .3
	MOVWF   PORTC
	RETURN
    DATO5
	MOVLW   .5
	MOVWF   PORTC
	RETURN
    DATO7
	MOVLW   .7
	MOVWF   PORTC
	RETURN

    DATO2
	MOVLW   .2
	MOVWF   PORTC
	RETURN
    DATO4
	MOVLW   .4
	MOVWF   PORTC
	RETURN
    DATO6
	MOVLW   .6
	MOVWF   PORTC
	RETURN
    DATO8
	MOVLW   .8
	MOVWF   PORTC
	RETURN

	END 
