
     LIST    P=16F887
     #include <P16F887.INC>
    
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
     CBLOCK 0x20
    CONTADOR   
    FLAG
    T1    
     AUX     
    ENDC
    
     
    ORG 0x00
    GOTO INICIO
     
INICIO     
    BANKSEL ANSELH
    CLRF ANSELH
    BANKSEL TRISA
    CLRF TRISD
    BSF TRISA,0
    
    BANKSEL PORTA
    MOVLW 0x00
    MOVWF FLAG
    MOVWF CONTADOR
L1
    BTFSC FLAG,0
    MOVLW .10
    SUBWF CONTADOR,W
    BTFSC STATUS,Z
    CLRF CONTADOR
    MOVF CONTADOR,W
    CALL TABLA
    MOVWF PORTD
    
    MOVF PORTB,W
    MOVWF AUX
    CALL RETARDO
    
    BTFSC PORTB,0
    GOTO L1
    BTFSS AUX,0
    GOTO L1
    CALL ESTADO
    GOTO L1
    
ESTADO
    COMF FLAG,F
    
RETARDO
    MOVLW .250
    MOVWF T1
B1
    DECFSZ T1,F
    GOTO B1
    RETURN
    
   


TABLA
    ADDWF PCL,F
    RETLW 0X3F
    RETLW 0X06
    RETLW 0X5B
    RETLW 0X4F
    RETLW 0X66
    RETLW 0X6D
    RETLW 0X7D
    RETLW 0X07
    RETLW 0X7F
    RETLW 0X67
    
    END
 
    ;0x0BB
    ;0x155
    ;0x20F
    ;0x3F0