
LIST    P=16F887
#include <P16F887.INC>
    
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    CBLOCK 0x20
    SHIFTREG
    ENDC
    CBLOCK 0x70
    STATUS_TEMP
    W_TEMP
    ENDC
     
    ORG 0x00
    GOTO INICIO

    ORG 0x04
    GOTO INTER
    ORG 0x05
    
INICIO ;CONFIG PUERTO
    BANKSEL TRISB
    CLRF TRISB
    BSF TRISB,RB0
    BANKSEL PORTB
    CLRF PORTB
    BSF SHIFTREG,0
    ;Interrupcion por RBO
    BCF OPTION_REG,INTEDG
    BCF INTCON,INTF
    BSF INTCON,INTE
    BSF INTCON,GIE
    GOTO $
    
INTER ; GUARDO CONTEXTO
    MOVWF W_TEMP        ;GUARDAR EN 0x70 (todos los bancos)
    SWAPF STATUS,W	
    MOVWF STATUS_TEMP
    ;CONSULTA DE LA FUENTE A LA INTERRUPCION
    
    ;RUTINA DE SERVICIO A LA INTERRUPCION
    BCF STATUS,C
    RLF SHIFTREG,F
    MOVLW 0x02
    BTFSC SHIFTREG,4
    MOVWF SHIFTREG
    MOVF SHIFTREG,W
    MOVWF PORTB

SALIR	;RECUPERO CONTEXTO
    SWAPF STATUS_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,F
    BCF INTCON,INTF
    RETFIE
    END
    