
LIST    P=16F887
#include <P16F887.INC>
    
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    #DEFINE BOTON PORTB,RB0
    
    NUM		EQU 0x20
    W_TEMP	EQU 0x70
    STATUS_TEMP EQU 0x71
 
    ORG 0x00
    GOTO INICIO
    ORG 0x04
    GOTO ISR
    ORG 0x05
INICIO
    BANKSEL	ANSELH
    CLRF	ANSELH
    CLRF	ANSEL
    BANKSEL	TRISB
    MOVLW	.1
    MOVWF	TRISB
    ;BCF		OPTION_REG,RBPU
    BANKSEL	PORTB
    CLRF	PORTB
    MOVF	W,NUM
    BSF		OPTION_REG,INTEDG
    
    BSF		OPTION_REG,INTF  ;

    BSF		INTCON,INTE
    BSF		INTCON,GIE
    GOTO	$
   
    BTFSS	BOTON
    BSF		OPTION_REG,INTF
    MOVWF	PORTB
    GOTO	$
    
ISR
    MOVF	W,W_TEMP
    MOVWF	STATUS
    MOVF	W,STATUS_TEMP
    RLF		NUM,F
    MOVLW	.2
    BTFSS	NUM,4
    MOVWF	NUM
    MOVF	NUM,W
    MOVWF	PORTB

    MOVF	STATUS_TEMP,W
    MOVWF	    STATUS
    MOVF	    W_TEMP,W
    BCF		INTCON,INTF
    RETFIE
    
    END
    
    