LIST P=16F887
#INCLUDE<PIC16f887>
    
; __config 0x20F4
 __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 
    ORG	0X00
    GOTO INICIO
    ORG 0X04
    GOTO ISR
    ORG 0X05
INICIO
    BANKSEL ANSEL
    CLRF    ANSEL
    CLRF    ANSELH
    BANKSEL TRISA
    BSF	    TRISA,RA4
    BSF	    TRISB,RB0
    CLRF    TRISD
    BANKSEL PORTD
    CLRF    PORTD
    BSF	    INTCON,GIE
    BSF	    INTCON,INTE
    
    BTFSC   PORTA,RA4
    GOTO    $-1
    BSF	    INTCON,INTE
    BCF	    INTCON,INTF
    BSF	    INTCON,GIE
    
    MOVLW   0XFF
    MOVWF   PORTD
    CALL    DELAY_1SEG
    CLRF    PORTD
    CALL    DELAY_1SEG
    GOTO    $-5

DELAY_1SEG
    MOVLW	D'5'
    MOVWF	T1
L1	
    MOVLW	D'100'
    MOVWF	T2
L2
    MOVLW	D'200'
    MOVWF	T3
L3
    DECFSZ	T3,F
    GOTO	L3
    DECFSZ	T2,F
    GOTO	L2
    DECFSZ	T1,F
    GOTO	L1
    RETURN
	
ISR
    MOVF    W,W_TEMP
    SWAPF   STATUS,W
    MOVF    W,STATUS_TEMP
    CALL    DELAY
    CALL    DELAY
    CALL    DELAY
    SWAPF   STATUS_TEMP,W
    MOVF    W,STATUS
    MOVWF   W_TEMP
    BCF	    INTCON,INTF
    RETFIE
 
    END
    