
     LIST    P=16F887
     #include <P16F887.INC>
    
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    ORG 0x00
    GOTO INICIO
    
    ORG 0x05
INICIO
    BANKSEL TRISA
    BSF TRISA,4
    BSF TRISB,0
    BCF TRISB,2
    BCF TRISB,3
    BANKSEL ANSELH
    CLRF ANSELH
    CLRF ANSEL
   
PULS 
    BANKSEL PORTA
    BTFSS PORTA,4
    BSF PORTB,2
    BTFSC PORTA,4
    BCF PORTB,2
    
    
    BTFSS PORTB,0
    BSF PORTB,3
    BTFSC PORTB,0
    BCF PORTB,3
    
    GOTO PULS
    
    
    END
    
;inicio
 ;   BANKSEL ANSEL
  ;  CLRF ANSEL
   ; CLRF ANSELH
    ;BANKSEL TRISA
    ;BSF TRISA,RA4
    ;BSF TRISF,RB0
    ;CLRF PORTD
    ;BANKSEL PORTA
;BUCLE
    ;CLRF AUX
    ;BTFSC PORTA,RA0
    ;BSF AUX,0
   ; MOVF PORTB,W
    ;ADDWF AUX,W
   ; CALL TABLA
   ; MOVF PORTD
   ; GOTO BUCLE
    
;TABLA
   ; ADDWF PCL,F
   ; RETLW 0xAA
  ;  RETLW 0x55
  ;  RETLW 0x0F
   ; RETLW 0xF0
