
LIST    P=16F887
#include <P16F887.INC>
    
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    CBLOCK 0x20
    VAR1
    VAR2
    VAR3
    CONT1
    MAX
    CONT2
    T1
    T2
    T3
    ENDC
    
    
    ORG 0X00
    GOTO INICIO
    ORG 0X04
    GOTO ISR
    ORG 0X05
    
INICIO
    BANKSEL TRISB
    CLRF    TRISB
    BSF	    TRISA,0
    
    MOVLW   B'1000000'
    BSF	    OPTION_REG,GIE
    
    ;CONFIGURO COMO TEMPORIZADOR TMR0
    BSF	    OPTION_REG,T0CS
    BSF	    OPTION_REG,PSA
    BSF	    OPTION_REG,PS2
    BSF	    OPTION_REG,PS1
    BSF	    OPTION_REG,PS0  ;PSA en 1:256
    ;PORTB = 0
    BANKSEL PORTB
    CLRF    PORTB
    
    ;CONFIGURAR LAS INTERRUPCIONES
    BSF	    INTCON,T0IE
    BSF	    INTCON,GIE
    
    BANKSEL TMR0
    MOVLW   .250
    MOVWF   TMR0
    
    
	
RETARDO
	MOVLW	D'1'
	MOVWF	T1
L1	
	MOVLW	D'1'
	MOVWF	T2
L2
	MOVLW	D'2'
	MOVWF	T3
L3
	DECFSZ	T3,F
	GOTO	L3
	DECFSZ	T2,F
	GOTO	L2
	DECFSZ	T1,F
	GOTO	L1
    
ISR
    BCF	    INTCON,GIE
    BTFSS   INTCON,T0IF
    GOTO    SALIDA
    MOVLW   0XFF
    MOVWF   PORTB
    BCF	    INTCON,T0IF
    
SALIDA
    BSF	    INTCON,GIE
    RETFIE
    END