
    LIST    P=16F887
     
    #include <P16f887.INC>
    
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    #DEFINE LED PORTB,RB0
    #DEFINE PULSADOR PORTC,RC0
    
    CONT EQU 0X21
 

    ORG 0X00
    GOTO INICIO
    
    ORG 0X05
INICIO    
    BANKSEL TRISB
    CLRF    TRISB
    BANKSEL PORTB
    MOVLW   B'10101011'
    MOVWF   PORTB
    
FIN
    GOTO FIN
    
    END
  