; ELECTRÓNICA DIGITAL II
    
; --------  Ejercicio 5.4  ---------
    
; Autor:
    ; Ignacio Vizgarra
    
; Profesor:
    ; Martin Del Barco
     
; Fecha: 19/05/2025

LIST    P=16F887
#include <P16F887.INC>
    
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    CBLOCK  0x20
	BANDERA
	CONT_DISP
	ACTIVADOR_PORT
	CONT_TMR
    ENDC
     CBLOCK 0x30
	 SEG1
	 SEG2
	 MIN1
	 MIN2
	 HORA1
	 HORA2
     ENDC

    
    ORG	    0X00
    GOTO    INICIO
    ORG	    0X04
    GOTO    ISR
    ORG	    0X05

INICIO 
    CALL INICIALIZACION
LOOP
    
INICIALIZACION
    BANKSEL ANSEL
    CLRF    ANSEL
    CLRF    ANSELH
    BANKSEL TRISD
    CLRF    TRISD
    CLRF    TRISA
    BSF	    TRISB,0
    
    BCF OPTION_REG,INTEDG
    BSF	INTCON,GIE
    BSF	INTCON,INTE
    BSF	INTCON,T0IE
    
    BSF WPUB,0
    ;VARIABLES CON LAS QUE VOY A TRABAJAR
	 CLRF W_TEMP
	 CLRF STATUS_TEMP
	 CLRF SEG1
	 CLRF SEG2
	 CLRF MIN1
	 CLRF MIN2
	 CLRF HORA1
	 CLRF HORA2
	 CLRF BANDERAS
	 CLRF CONT_DE_DIS
	 MOVLW 0x7F
	 MOVWF ACTIVAR_PORT
	 MOVLW .250
	 MOVWF CONTADOR250
	 
	 MOVLW	0xFF
	 MOVWF	PORTA
	 
	RETURN
ISR
	 MOVWF W_TEMP
	 SWAPF STATUS, W
	 MOVWF STATUS_TEMP
	 
	 ;TESTEO DE DÓNDE VINO LA INTERRPCIÓN Y DERIVO
	 BTFSC INTCON, INTF
	 CALL SUBRRUTINA_RB0
	 
	 ; RECUPERO CONTEXTO
	 SWAPF STATUS_TEMP, W
	 MOVWF STATUS
	 SWAPF W_TEMP, F
	 SWAPF W_TEMP, W
	 RETFIE
    
    SUBRRUTINA_RB0
	BCF INTCON,INTF
	BSF BANDERA,0
	RETURN
	