
LIST    P=16F887
#include <P16F887.INC>
    
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    CBLOCK 0x20
    VAR1
    VAR2
    VAR3
    CONT1
    MAX
    CONT2
    ENDC
    
    
    ORG 0X00
    GOTO INICIO
    ORG 0X04
    GOTO ISR
    ORG 0X05
    
INICIO
    BANKSEL TRISB
    CLRF    TRISB
    
    ;CONFIGURO COMO TEMPORIZADOR TMR0
    BCF	    OPTION_REG,T0CS
    BCF	    OPTION_REG,PSA
    BSF	    OPTION_REG,PS2
    BSF	    OPTION_REG,PS1
    BSF	    OPTION_REG,PS0  ;PSA en 1:256
    ;PORTB = 0
    BANKSEL PORTB
    CLRF    PORTB
    
    ;CONFIGURAR LAS INTERRUPCIONES
    BSF	    INTCON,T0IE
    BSF	    INTCON,GIE
    
ISR
    BCF	    INTCON,GIE
    BTFSS   INTCON,T0IF
    GOTO    SALIDA
    INCF    PORTB
    BCF	    INTCON,T0IF
    
SALIDA
    BSF	    INTCON,GIE
    RETFIE
    
LOOP
    GOTO LOOP

    END