list p=16f887
#include<PIC16f887.INC>
    
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

    CBLOCK 0x20
    CONTADOR_DESBORDAMIENTOS
    CONT 
    AUX
    ENDC
    
    CBLOCK 0x70
    T1
    ENDC
    
    ORG 0x00
    GOTO INICIO
    
    ORG 0x05

INICIO ;Inicializacion de los puertos
    BANKSEL ANSEL
    CLRF ANSELH
    CLRF ANSEL
    BANKSEL TRISA
    BSF TRISB,RB0
    MOVLW 0xFF
    MOVWF TRISD
    MOVLW .0
    MOVWF CONT
    MOVLW .10
    MOVWF AUX

    
    BANKSEL PORTA
    BTFSC PORTB,RB0
    INCF CONT , F
    MOVF CONT,PORTB
    GOTO DELAY_1S
    
DELAY_1S
    MOVLW .255
    MOVWF T1
B1  
    DECFSZ T1,F
    GOTO B1
    RETURN
    